### ISSUE TITLE
Update agent to conform to symfony style guide

### ISSUE THREAD

**Issue by skluck** [hal-platform/hal#14]
http://symfony.com/blog/new-in-symfony-2-8-console-style-guide

**Comment by skluck** [comment]
This should include updating the way the **Commands** are built (including "lazy command" system) to take advantage of any improvements since symfony 3.

**Comment by nagibyro** [comment]
Possible changes to output

current
```
[Starting Build] Resolving build properties
[Starting Build] Application: Sample App
[Starting Build] Environment: docker-agent
[Starting Build] Build: b2.64ShR2G
[Starting Build] Downloading github repository
[Starting Build] Unpacking github repository
[Starting Build] Reading .hal9000.yml
[Building] Building
....
```

Symfony Style Guide
```
Starting Build
--------------

 * Resolving build properties

 * Application: Sample App

 * Environment: docker-agent

 * Build: b2.64RHxUs

 * Downloading github repository

 * Unpacking github repository

 * Reading .hal9000.yml
```

I kind of like the current output better than Symfony Style Guides output since a full build in the current format will output roughly 25 - 30 lines of output where symfony styles put new lines after everything which leads to doubling so its hard to see whole output without scrolling.

**Comment by nagibyro** [comment]
Moving this in the backlog for more design discussion before proceeding.

**Comment by nagibyro** [comment]
@skluck I'll try my hand at the `RemoveBuildCommand`

**Comment by skluck** [comment]
ok.

We actually don't really need remove build, list builds, or the two docker ones anymore. We'll wait until some of the other features are added (api-driven artifact repository, probably in early march) before we remove them.

The docker commands aren't needed because the agents won't be building dockerfiles and dont need to do any cleanup, everything must come from dockerhub or a registry. Eventually we should be able to build apps' dockerfiles if they include them in their project, but thats a ways off.

Remove/list builds are ops-focused commands which came about because the ui has no direct access to the build archives and can't delete build files. But if we're switching to an api-driven artifact repository, deletions can happen from the ui. No need to log into an agent.

I would like to have a more full-featured cli at some point, but maybe that happens when the cli is more api-driven and stripped down a bit which would make it easier to port to another language.

**Comment by skluck** [comment]
#### BuildCommand

```
Runner - Run build
==================

[1/7] Resolving configuration
-----------------------------

 * Build: b2.5KV2rzW
 * Application: SSO Demo (ID: 9)
 * Environment: test (ID: 1)

[2/7] Downloading source code
-----------------------------

 * Source repository: sample/project
 * Source reference: 6f9dca065a9d8ff60737e41fb0f46fa74f26c57a
 * Target: /project/.build/hal9000-download-b2.5KV2rzW.tar.gz

[3/7] Unpacking source code
---------------------------

 * Source file: /project/.build/hal9000-download-b2.5KV2rzW.tar.gz
 * Build directory: /project/.build/hal9000-build-b2.5KV2rzW

[4/7] Reading .hal.yml configuration
------------------------------------

 * Application configuration:

 ----------------- ---------------------------- 
  Configuration     Value                       
 ----------------- ---------------------------- 
  system            "unix"                      
  dist              "."                         
  exclude           [                           
                        "config/database.ini",  
                        "data/"                 
                    ]                           
  build             [                           
                        "bin/deploy"            
                    ]                           
  build_transform   []                          
  pre_push          []                          
  deploy            []                          
  post_push         []                          
 ----------------- ---------------------------- 

[5/7] Running build process
---------------------------

 * System: unix

 Commands:
 * bin/deploy

[Building - Unix] Building on unix
[Building - Unix] Validating unix configuration
[Building - Unix] Exporting files to build server
[Building - Unix] Running build command
[Docker] Validating specified Docker image "legacy"
[Docker] Building container "hal9000/legacy"
[Docker] Starting Docker container
[Docker] Docker container "4f2f91f0bb1be77a38c3348722acb77521254d6710400756e4a9052eedd8fa74" started
[Docker - Build] Running build command [ bin/deploy ] in Docker container
[Docker] Cleaning up container "4f2f91f0bb1be77a38c3348722acb77521254d6710400756e4a9052eedd8fa74"
[Building - Unix] Importing files from build server
[Shutdown] Cleaning up remote unix build server

[6/7] Packing build artifact
----------------------------

 * Build directory: /project/.build/hal9000-build-b2.5KV2rzW
 * Artifact path: .
 * Artifact file: /project/.build/hal9000-build-b2.5KV2rzW

[7/7] Exporting build artifact
------------------------------

 * Artifact file: /project/.build/hal9000-build-b2.5KV2rzW.tar.gz
 * Repository storage: /project/.archive/2016-01/hal9000-b2.5KV2rzW.tar.gz

Command Usage Statistics
------------------------

 Memory Usage: 12.59 / 384 MB (Peak: 14 MB)
 Elapsed Time: 11 seconds

Build clean-up
--------------

 Build artifacts to remove:
 * /project/.build/hal9000-download-b2.5KV2rzW.tar.gz
 * /project/.build/hal9000-build-b2.5KV2rzW
 * /project/.build/hal9000-build-b2.5KV2rzW.tar.gz

 Disconnecting all open SSH connections.

                                                                                                                        
 [OK] Build was run successfully.                                                                                       
                                                                                                                        
```

Some inconsistency with `listing`, but its fine for now. Would be nice if symfonyStyle supported sub lists.

**Comment by nagibyro** [comment]
Yeah the commands as a sub list would look a lot nicer but still this does look better than before.

**Comment by skluck** [comment]
### Changed
- `build:create` to `management:build:create`
- `push:create` to `management:release:create`
- `build:remove` to `management:build:remove`
- `build:build` to `runner:build`
- `push:push` to `runner:deploy`
- `worker:push` to `worker:deploy`

### Updated
- `docker:refresh`
- `docker:status`
- `worker:build`

### Added
- `management:build:start` (Calls `m:build:create` and `r:build`)
- `management:release:start` (Calls `m:release:create` and `r:deploy`)

### Removed
- `server:connections`
- `builds:list`
