### ISSUE TITLE
Ensure Hal UI and Hal Agent support PHP 7.1

### ISSUE THREAD

**Issue by skluck** [hal-platform/hal#3]
This includes all dependencies.

Probably includes the following:
- [x] knplabs/github (agent)
- [x] knplabs/github (ui)
- [x] phpseclib (agent)
- [x] Update to latest 2.x symfony components (ui)
- [x] Update to latest 3.x symfony components (agent)
- [x] Update to latest 2.x slim/slim (ui)
- [x] Update to latest 2.x twig (ui)
- [x] Update to latest 6.x guzzle (ui)
- [x] Update to latest 6.x guzzle (agent)

**Comment by nagibyro** [comment]
All libraries updated -- Agent unit tests pass in 7.1 and been running the UI in 7.1 for the last few days of development.
