### ISSUE TITLE
Add health status test suite for the API

### ISSUE THREAD

**Issue by skluck** [hal-platform/hal#45]
In tandem with #44 (Add health status endpoint), we should be able to run a test against the hal instance that traverses the entire API to ensure every endpoint returns an `OK` response. This is pretty easy to do since the API is hypermedia-based and a single test could crawl the entire API from the index.

This test could be run on a schedule to ensure hal is healthy and [still alive](https://www.youtube.com/watch?v=Y6ljFaKRTrI).

**Comment by nagibyro** [comment]
we can store the health status icons in S3 then we know we can always get to them :trollface:
