### ISSUE TITLE
Harden docker security

### ISSUE THREAD

**Issue by skluck** [hal-platform/hal#53]
As we run all **insecure** command such as build an deploy commands in docker containers, we need to ensure our docker environment is secure and safe from injection, jailbreaking, or other nefarious commands.

Can the following example break hal? Then this issue isn't complete.
https://github.com/amoffat/dockerbomb

Resources:
- http://www.infoworld.com/article/3030558/application-virtualization/docker-goes-rootless-and-thats-a-good-thing.html
- (⚠️ pdf) https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.13.0_Benchmark_v1.0.0.pdf

**Comment by nagibyro** [comment]
At OSCON they talked about [seccomp profiles](https://docs.docker.com/engine/security/seccomp/#passing-a-profile-for-a-container) which restrict which system calls the container can make. Might be one good mitigation strategy.
