### ISSUE TITLE
Migration Deletes and Updates

### ISSUE THREAD

**Issue by nagibyro** [hal-platform/hal#59]
## Issue
We didn't put in any handling of database deletes in the DB or doctrine for most entity relationships. 
- `Targets` set credential_id to null on `Credential` delete.
- `UserTokens` deleted if user deleted
- `UserPermissions` deleted if user deleted

Also we need to decided if we should cascade operations in Doctrine or the DB. From the Doctrine docs we might have performance issues using `cascade: ['all']` or similar in doctrine (as we do for the `User` entity).

>  Cascade operations are performed in memory. That means collections and related entities are fetched into memory, even if they are still marked as lazy when the cascade operation is about to be performed. However this approach allows entity lifecycle events to be performed for each of these operations. 

> However, pulling objects graph into memory on cascade can cause considerable performance overhead, especially when cascading collections are large. Makes sure to weigh the benefits and downsides of each cascade operation that you define. 

> To rely on the database level cascade operations for the delete operation instead, you can configure each join column with the onDelete option. See the respective mapping driver chapters for more information.

**Comment by skluck** [comment]
Originally, I wanted to have everything handled in the application layer - So the UI would have to explicitly delete every relation.

It's worth revisiting (or appropriately updating the UI/API to account for it)
