### ISSUE TITLE
Switch to open source MCP components

### ISSUE THREAD

**Issue by skluck** [hal-platform/hal#6]
### UI
- [x] Fully switch from `mcp-core` to `mcp-common`
- [x] Stop using `panthor-plugins`
- [x] Stop using `mcp-corp-account` and figure out what to do about login (for now, oauth2 later)
- [x] MCP Logger 3.0
- [x] MCP Cache 3.0

### Agent
- [x] MCP Logger 3.0

**Comment by nagibyro** [comment]
UI updated to MCP Cache 3.0 when #4 was closed.

**Comment by skluck** [comment]
All done here, master of hal-ui and hal-agent both updated.

There is now nothing blocking #19 so we can hopefully do that within a few weeks.
